n = input('Diite seu nome completo: ')
n1 = n.strip()
n2 = n1.upper()
n3 = n1.lower()
n4 = n1.title()
n5 = n1.split()
n6 = ''.join(n5)
esp = n1.count(' ')
print(f'Seu nome com as letras maiusculas: {n2}')
print(f'Seu nome com as letras minusculas: {n3}')
#print('Seu nome completo tem', len(n1)-(esp), ' letras.')
print('Seu nome completo tem ', len(n6), 'letras.')
print('Seu primeiro nome tem', len(n5[0]), ' letras.')
